apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-25hc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-25hc
    app.kubernetes.io/part-of: ci10t-777-0070-app
  name: devfile-sample-25hc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-25hc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-25hc
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0070-tenant/ci10t-777-0070-app/devfile-sample-25hc@sha256:947c3a03975abc778d1c1d43b04834b810534f53dc1b0447cab40f433c457ab6
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
